---
telegram_chat_id: "<telegram_chat_id_here>"
telegram_token: "<telegram_token_here>"
tailscale_auth_key: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          36643831316563636230616339656661626333306132353138616566636139336564333663383938
          3161326462396532643163663735336636613265663264630a666531333839383838386137653733
          34313861383232396438393636643732653531303237626266393131643263333162666561383437
          3036313833316433650a663661373634393861386638616364356334656666393335306232363334
          65616135333230643335653931616631343930623332316638656534396637343039313635653138
          30306439316565366230343465336264373061393431333865313061396531636436303530656661
          366464346432633534643734616462666130
