---
telegram_chat_id: "<telegram_chat_id_here>"
telegram_token: "<telegram_token_here>"
tailscale_auth_key: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          33363231623638666266326635343633393733636362373131663338623365633764653934333465
          3763383138306530383033323866613134643336396533340a643031393665333334626134326262
          34626333343364363439663561336532663863363961636662383830346362343632356236643330
          3035353533633438640a376535313766356663353061333465323839646532353034666639376166
          63366164366662633038393932343535373331386438326135633865393165656663656239613431
          34623138386339323432376230653665373037633061623361386366323362316264336634306462
          303165383936633830633664366336383265
